p8105_hw3_hc3654
================

``` r
library(p8105.datasets)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
data("instacart")
```

# Problem 1:

## Describe dataset:

This dataset mainly contains the order information from the instacart
app. Some key values: user_id：unique identity of each customer,
order_hour_of_day: record the time for order replace, order_dow: record
the weekday for the order replace, product_name, aisle and which
department the order item belong. From observation I found their are
49688 unique product, 134 unique aisle and 21 unique department in the
dataset.

## Q1: How many aisles are there, and which aisles are the most items ordered from?

``` r
p1q1 <- instacart |> 
  group_by(aisle) |> 
  summarise(Total_order = n()) |> 
  arrange(desc(Total_order))

p1q1
```

    ## # A tibble: 134 × 2
    ##    aisle                         Total_order
    ##    <chr>                               <int>
    ##  1 fresh vegetables                   150609
    ##  2 fresh fruits                       150473
    ##  3 packaged vegetables fruits          78493
    ##  4 yogurt                              55240
    ##  5 packaged cheese                     41699
    ##  6 water seltzer sparkling water       36617
    ##  7 milk                                32644
    ##  8 chips pretzels                      31269
    ##  9 soy lactosefree                     26240
    ## 10 bread                               23635
    ## # ℹ 124 more rows

**Comment:** There are **134** distinct aisles, and the **Fresh
Vegetable** have the most items ordered from.

## Q2: Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more than 10000 items ordered. Arrange aisles sensibly, and organize your plot so others can read it.

``` r
p1q2 <- 
p1q1 |> 
  filter(Total_order > 10000)|> 
  ggplot(aes(x = reorder(aisle,Total_order), y = Total_order,fill = Total_order))+
           geom_col()+
  coord_flip()+
  labs(
    x = "Aisle", y = "Total orders", title = "Figure shows the relates with aisle and their order among")
p1q2
```

![](p8105_hw3_hc3654_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

**Comment:** Here is the graph for the aisles which more than 10000
orders. We can see there are total **39** aisles are in the graph.

## Q3: Make a table showing the three most popular items in each of the aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”. Include the number of times each item is ordered in your table

``` r
p1q3 <- instacart |> 
  group_by(aisle,product_name) |> 
  summarise(product_sale = n()) |> 
  arrange(aisle, desc(product_sale)) |> 
  slice_head(n = 3)
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the
    ## `.groups` argument.

``` r
p1q3
```

    ## # A tibble: 402 × 3
    ## # Groups:   aisle [134]
    ##    aisle                  product_name                              product_sale
    ##    <chr>                  <chr>                                            <int>
    ##  1 air fresheners candles Air Effects Linen & Sky Scent Air Freshe…           36
    ##  2 air fresheners candles After The Rain Gel Air Freshener                    32
    ##  3 air fresheners candles Air Effects Linen & Sky Air Refresher               30
    ##  4 asian foods            Organic Sea Salt Roasted Seaweed Snacks            345
    ##  5 asian foods            Sriracha Chili Sauce                               188
    ##  6 asian foods            Coconut Milk                                       185
    ##  7 baby accessories       Free & Clear Unscented Baby Wipes                  225
    ##  8 baby accessories       Totz Toothbrush Extra Soft 18+ Months               23
    ##  9 baby accessories       Swaddlers Size 4 Giant Pack Diapers                 10
    ## 10 baby bath body care    Calming Shampoo & Bodywash                          18
    ## # ℹ 392 more rows

**Comment:** Here is the table for the top 3 popular product for each
aisle and their times by order. For example: The top 3 item for asian
foods are Organic Sea Salt Roasted seaweed Snacks, Sriracha Chili Sauce
and Coconut Milk, there are 345, 188, and 185 respectively.

## Q4: Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).

``` r
p1q4 <- instacart |> 
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") |> 
  group_by(product_name, order_dow) |> 
  summarise(mean_hour = mean(order_hour_of_day)) |> 
  pivot_wider(
  names_from = order_dow,
  values_from = mean_hour
  ) 
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the
    ## `.groups` argument.

``` r
knitr::kable(p1q4,
             col.names = c("Product","Sunday", "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday"), digits =2 )
```

| Product          | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
|:-----------------|-------:|-------:|--------:|----------:|---------:|-------:|---------:|
| Coffee Ice Cream |  13.77 |  14.32 |   15.38 |     15.32 |    15.22 |  12.26 |    13.83 |
| Pink Lady Apples |  13.44 |  11.36 |   11.70 |     14.25 |    11.55 |  12.78 |    11.94 |

**Comment:** Here is the readers table showing the mean hour for Coffee
Ice and Pnnk Lady Apples are orderd on each day of the week.The most
ordered day for Coffee Ice Cream is **Tuesday** and the least is
**Friday**. The most ordered day for Pink Lady Apples are **Wednesday
**and the least is **Monday**.

# Problem 2:

## 1.Import datasets

``` r
ny_zillow_df <- 
  read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",na = c("NA", ".", " "))
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zip_df <- 
  read_csv("zillow_data/Zip Codes.csv")
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Q1: There are 116 months between January 2015 and August 2024. How many ZIP codes are observed 116 times? How many are observed fewer than 10 times? Why are some ZIP codes are observed rarely and others observed in each month?

``` r
p2 <- ny_zillow_df |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = x2015_01_31 : x2024_08_31,
    names_to = "date",
    values_to = "rental_fee"
  ) |> 
  mutate(date = sub("x", "",date))

p2q1 <-  p2 |> 
  group_by(region_name) |>
  summarise(n_months = sum(!is.na(rental_fee)), .groups = "drop")


obs116 <- p2q1 |> 
  filter(n_months == 116) |> 
  count()


obs10 <- p2q1 |> 
  filter(n_months < 10) |> 
  count()

p2q1 <- bind_cols(obs116,obs10)
```

    ## New names:
    ## • `n` -> `n...1`
    ## • `n` -> `n...2`

``` r
knitr::kable(p2q1, col.names = c("Full months", "Less than 10"))
```

| Full months | Less than 10 |
|------------:|-------------:|
|          48 |           26 |

**Comment:** During January 2015 and August 2024. There are **48** zip
codes are observed 116 months times and **26** zip codes are observed
less than 10 months.

## Q2: Create a reader-friendly table showing the average rental price in each borough and year (not month). Comment on trends in this table.

``` r
p2q2 <- p2 |> 
  separate(date, into = c("year", "month", "day"),sep = "_") |> 
  group_by(year, county_name) |> 
  summarise(avg_rental = mean(rental_fee, na.rm = TRUE)) |> 
  pivot_wider(
    names_from = county_name,
    values_from = avg_rental
  )
```

    ## `summarise()` has grouped output by 'year'. You can override using the
    ## `.groups` argument.

``` r
p2q2
```

    ## # A tibble: 10 × 6
    ## # Groups:   year [10]
    ##    year  `Bronx County` `Kings County` `New York County` `Queens County`
    ##    <chr>          <dbl>          <dbl>             <dbl>           <dbl>
    ##  1 2015           1760.          2493.             3022.           2215.
    ##  2 2016           1520.          2520.             3039.           2272.
    ##  3 2017           1544.          2546.             3134.           2263.
    ##  4 2018           1639.          2547.             3184.           2292.
    ##  5 2019           1706.          2631.             3310.           2388.
    ##  6 2020           1811.          2555.             3107.           2316.
    ##  7 2021           1858.          2550.             3137.           2211.
    ##  8 2022           2054.          2868.             3778.           2406.
    ##  9 2023           2285.          3015.             3933.           2562.
    ## 10 2024           2497.          3127.             4078.           2694.
    ## # ℹ 1 more variable: `Richmond County` <dbl>

**Comment:** This table presents the average rental prices by borough
from 2015 to 2024. Rental prices show an overall upward trend across all
boroughs, though the pace differs by location. Richmond County has
missing data from 2015–2019, but from 2020 onward, it follows a steady
increase similar to other boroughs. New York County consistently records
the highest rental prices, while Bronx County remains the most
affordable. Minor fluctuations, particularly between 2019 and 2021,
likely reflect the market disruptions caused by the COVID-19 pandemic.

## Q3: Make a plot showing NYC Rental Prices within ZIP codes for all available years. Your plot should facilitate comparisons across boroughs. Comment on any significant elements of this plot.

``` r
p2g1 <- 
p2 |> 
  group_by(region_name, date, county_name) |> 
  summarise(avg_price = mean(rental_fee, na.rm = TRUE), .groups = "drop") |> 
  mutate(date = ymd(date))|> 
  ggplot(aes(x = date, y = avg_price, group = region_name, color = avg_price)) +
  geom_line(alpha = 0.5)+
  scale_x_date(
  breaks = as.Date(c("2015-01-01", "2018-01-01", "2021-01-01", "2024-01-01")),
  labels = c("2015", "2019", "2021", "2024")
)+
  geom_smooth(aes(group = county_name), method = "loess", se = FALSE, size = 1.2, color = "orange", alpha = 0.6)+

  theme(
  axis.text.x = element_text(angle = 45, hjust = 1) 
)+
  facet_grid(~county_name)+
  labs( x= "Average Price", y = "Time", title = "Average Rental Price Over Time Separated by County" )
```

    ## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
    ## ℹ Please use `linewidth` instead.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

``` r
p2g1
```

    ## `geom_smooth()` using formula = 'y ~ x'

    ## Warning: Removed 6834 rows containing non-finite outside the scale range
    ## (`stat_smooth()`).

    ## Warning: Removed 6804 rows containing missing values or values outside the scale range
    ## (`geom_line()`).

![](p8105_hw3_hc3654_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

**Comment:** This plot illustrates the trends in NYC rental prices
across ZIP codes over time, separated by boroughs. The smooth lines
highlight the overall increase in rental prices, though the patterns
vary across boroughs. During the COVID-19 pandemic period (around
2019–2021), there are noticeable fluctuations in several boroughs,
reflecting market instability. New York County consistently shows the
highest rental prices, with some ZIP codes averaging above \$6000, which
stands out significantly compared to other boroughs. This suggests that
rental markets in Manhattan are driven by different economic factors
than in the outer boroughs.

## Q4: Compute the average rental price within each ZIP code over each month in 2023. Make a reader-friendly plot showing the distribution of ZIP-code-level rental prices across boroughs; put differently, your plot should facilitate the comparison of the distribution of average rental prices across boroughs. Comment on this plot

``` r
p2g2 <- p2 |> 
  separate(date, into = c("year", "month", "day"),sep = "_") |> 
  filter(year == 2023) |> 
  group_by(region_name, month, county_name) |> 
  summarise(avg_price = mean(rental_fee, na.rm = TRUE), .groups = "drop")|> 
  ggplot(aes(x = as.numeric(month), y = avg_price, group = region_name,color = avg_price))+
  geom_line()+
  geom_smooth(aes(group = county_name), method = "loess", se = FALSE, size = 1.2, color = "yellow", alpha = 0.6)+
  facet_grid(~ county_name)+
  scale_x_continuous(breaks = c(1,3,6,9,12))+
  labs(x = "Month", y = "Average Rental Fee", Title = "Relationship between Average Rental Fee and Month")+
  theme_bw() 

p2g2
```

    ## `geom_smooth()` using formula = 'y ~ x'

    ## Warning: Removed 333 rows containing non-finite outside the scale range
    ## (`stat_smooth()`).

    ## Warning: Removed 330 rows containing missing values or values outside the scale range
    ## (`geom_line()`).

![](p8105_hw3_hc3654_files/figure-gfm/unnamed-chunk-10-1.png)<!-- -->

**Comment:** From this plot, we see that average rental prices vary
noticeably across boroughs. New York County (Manhattan) has the highest
ZIP-code rental levels, often above \$6000, while Bronx and Richmond
Counties remain the lowest, around \$2000–\$2500. Across most boroughs,
many ZIP codes show seasonal peaks in the fall, which may be linked to
the timing of school and job cycles when demand for housing increases.
In contrast, the high-priced ZIP codes in New York County do not follow
this seasonal pattern, likely because rents there are driven more by
professional demand and long-term residents rather than academic cycles.

## Q5: Combination

``` r
library(patchwork)

combined <- p2g1 / p2g2 
if (!dir.exists("results")) dir.create("results")
ggsave("results/combined_plot.png", combined, width = 12, height = 10, dpi = 300)
```

    ## `geom_smooth()` using formula = 'y ~ x'

    ## Warning: Removed 6834 rows containing non-finite outside the scale range
    ## (`stat_smooth()`).

    ## Warning: Removed 6804 rows containing missing values or values outside the scale range
    ## (`geom_line()`).

    ## `geom_smooth()` using formula = 'y ~ x'

    ## Warning: Removed 333 rows containing non-finite outside the scale range
    ## (`stat_smooth()`).

    ## Warning: Removed 330 rows containing missing values or values outside the scale range
    ## (`geom_line()`).

# Problem 3:

``` r
accel_df <- 
  read.csv("nhanes_accel.csv", na = c("NA",".", ""))

covar_df <- 
  read.csv("nhanes_covar.csv", skip = 4, na = c("NA",".", ""))|> 
  na.omit() 

p3 <- 
  left_join(covar_df, accel_df, by = "SEQN") |> 
  filter(age >= 21) |> 
  mutate(sex = case_when(
   sex == 1 ~ "male",
   sex == 2 ~ "female"
  ),
    education = case_when(
      education == 1 ~"Less than high school",
      education == 2~ "High school equivalent",
      education == 3 ~ "More than high school"
    )
  )
```

## Q1 : Produce a reader-friendly table for the number of men and women in each education category, and create a visualization of the age distributions for men and women in each education category. Comment on these items.

``` r
p3q1 <- p3 |> group_by(sex, education) |> 
  summarise(number = n(), .groups = "drop") |> 
  pivot_wider(
    names_from = sex,
    values_from = number
  )

p3g1 <- p3|> 
  group_by(sex, education) |> 
  summarise(number = n(), .groups = "drop") |> 
  ggplot(aes(x = sex, y = number, fill = education)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7)+
  scale_fill_brewer(palette = "Set2")+
  theme_bw()

p3q1
```

    ## # A tibble: 3 × 3
    ##   education              female  male
    ##   <chr>                   <int> <int>
    ## 1 High school equivalent     23    35
    ## 2 Less than high school      28    27
    ## 3 More than high school      59    56

``` r
p3g1
```

![](p8105_hw3_hc3654_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->

**Comment:** From the table and visualization, we see that participants
with **More than high school** education are the largest group for both
men and women, while those with High school equivalent and Less than
high school have fewer participants. The distribution suggests that the
sample may be somewhat skewed toward higher education levels. When
looking at age distributions by education and sex, men and women appear
fairly similar across groups.

## Q2: Traditional analyses of accelerometer data focus on the total activity over the day. Using your tidied dataset, aggregate across minutes to create a total activity variable for each participant. Plot these total activities (y-axis) against age (x-axis); your plot should compare men to women and have separate panels for each education level. Include a trend line or a smooth to illustrate differences. Comment on your plot.

``` r
p3 |> 
  rowwise() |> 
  mutate(total = sum(c_across(min1:min1440))) |> 
  select(-c(min1:min1440)) |> 
  ggplot(aes(x = age, y = total, color = sex, shape = sex)) +
   geom_smooth(se = FALSE) +
  facet_wrap(~ education)+
  geom_point(alpha = 0.6)+
  theme_bw()
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

![](p8105_hw3_hc3654_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

**Comment:** The graphs are separated into three panels by education
level. 1. For the High school equivalent group, female participants
generally show higher daily activity than males across most ages.
Activity levels peak around age 40 for both sexes and then gradually
decline. 2. For the Less than high school group, male participants tend
to have higher daily activity than females, with both sexes peaking in
activity between ages 20 and 30 before showing a steady decline. 3. For
the More than high school group, females consistently maintain higher
daily activity than males across almost all ages, though both sexes show
a relatively flat activity pattern compared to the other groups.

## Q3: Accelerometer data allows the inspection activity over the course of the day. Make a three-panel plot that shows the 24-hour activity time courses for each education level and use color to indicate sex. Describe in words any patterns or conclusions you can make based on this graph; including smooth trends may help identify differences.

``` r
p3 |> 
  select(-age,-BMI) |> 
  pivot_longer(
    cols = starts_with("min"),
    names_to  = "minute",
    values_to = "activity",
    names_prefix = "min"
  ) |> 
  mutate(minute = as.integer(minute)) |> 
  group_by(education, sex, minute) |> 
  summarise(avg_activity = mean(activity), .groups = "drop") |> 
  ggplot(aes(x = minute, y = avg_activity, color = sex))+
  facet_wrap(~education)+
  geom_line(linewidth = 0.9, alpha = 0.4) +
  scale_color_manual(values = c(male = 'darkblue', female = "pink"))+
  scale_x_continuous(
    breaks = seq(0, 1440, by = 240),
    labels = function(x) sprintf("%02d", x / 60))+
  geom_smooth()+
  labs(x = "Time in a day", y = "Activity", Title = "The activity distribution for a day seperate by different category")+
  theme_bw()
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw3_hc3654_files/figure-gfm/unnamed-chunk-15-1.png)<!-- -->

**Comment:** This graph shows that across all three education levels,
participants’ activity levels are lowest during the early morning hours
(around 4 AM) and peak between approximately 8 AM and 8 PM, reflecting
typical daily sleep–wake cycles. The smooth trends further suggest that
women consistently exhibit slightly higher peak activity levels than
men, particularly around midday and early afternoon. These differences,
though modest, appear across all education groups, indicating that
sex-related variation in activity is a general pattern rather than
specific to a single education level.
